[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && chmod -R 777 storage bootstrap/cache"

[deploy]
startCommand = "php artisan migrate --force; php artisan db:seed --force; php artisan config:clear; php artisan route:clear; php artisan view:clear; php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
restartPolicyCondition = "on-failure"
