[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader --no-scripts"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:clear && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyCondition = "on-failure"

